hourlyWage = float(input('input your hourly wage: '))
regHoursWorked = float(input('input the regular hours worked: '))
overtimeHours = float(input('input your overtime hours: '))
answer=(hourlyWage * regHoursWorked) + ((hourlyWage * 1.5) * overtimeHours)
print('your total pay is ',answer )
